platform :ios, '11.2'

target 'Viewer' do
    use_frameworks!
    
    pod 'Kingfisher', '~> 4.0'
    pod 'PromiseKit', '~> 6.4'
    pod 'OAuthSwift', '~> 1.2'
    pod 'KeychainSwift', '~> 11.0'
    pod 'PBImageView'
    
end

